### ISSUE TITLE
Support Pfizer search?

### ISSUE THREAD

**Issue by rodgerramjet26** [jakecoppinger/gp-vaccine-search#8]
Any chance this could also support searching for Pfizer availability? That is what my GP recommended for me. I saw the other Pfizer search site but I'm in regional Australia and that only supports capital cities.

**Comment by rodgerramjet26** [comment]
>  @``

**Comment by jakecoppinger** [comment]
Hey! Would be very keen to build this but haven't had the time recently. I might be able to implement later in week or weekend. PRs welcome!

**Comment by jakecoppinger** [comment]
If anyone wants to jump on this in the meantime, look at the checks here:
https://github.com/jakecoppinger/gp-vaccine-search/blob/8ba44b4ac208a176e5873ddbd1cc90bffda15933/backend/src/api.ts#L31

You'll likely need to duplicate `firstDoseReason()` for Pfizer, then modify `clinicInfoToAvailabilityIds()`. 

If you do please let me know so we aren't both working on it :)

**Comment by jakecoppinger** [comment]
I've implemented this, merged to `main` and deployed 🎉
